error: Introduction of a common error class
It was hard to align different error types handled
inside the Result class. Due to that, a new error
class for the budget tracker was added.